backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  repo: vaibhav201297/NetlifyCMS
media_folder: "_site/data/"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: false
# publish_mode: editorial_workflow
collections:
  - label: "Releases"
    name: "release-version"
    folder: "src/{{release}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Release Version", name: "release", widget: "string"}
    identifier_field: "{{release}}"
    slug: "{{release}}"
    

  - label: "Anatomical Structures"
    name: "models"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Description", name: "description", widget: "markdown"}
      - { label: "Creator(s)", name: "creators", widget: "list", allow_add: true, collapsed: true, field: {label: "Creator", name: "creator", widget: "relation", collection: "individuals", search_fields: ["orcid"], value_field: "orcid",display_fields: ["first_name","last_name","orcid"]  }}
      - { label: "Project Lead", name: "project_lead", widget: "relation",collection: "individuals", search_fields: ["orcid"], value_field: "orcid",display_fields: ["first_name","last_name","orcid","individual_type"]  } 
      - { label: "Reviewers(s)", name: "reviewers", widget: "list", allow_add: true, collapsed: true, field: {label: "Reviewer", name: "reviewer", widget: "relation", collection: "individuals", search_fields: ["orcid"], value_field: "orcid",display_fields: ["first_name","last_name","orcid"]  }}
      - { label: "Creation Date", name: "creation_date", widget: "date", default: ""}
      - { label: "License", name: "license", widget: "select",options: [
        { label: "Creative Commons Attribution 4.0 International (CC BY 4.0)", value: "CC BY 4.0" },
        { label: "MIT", value: "MIT"}]
        }
      - { label: "Publisher", name: "publisher", widget: "string"}
      - { label: "Funder", name: "funder", widget: "string"}
      - { label: "Award Number", name: "award_number", widget: "string"}
      - { label: "HuBMAP ID", name: "hubmap_id", widget: "string"}
      - { label: "Data Table", name: "datatable", widget: "file",media_library: {media_folder: "/static/files" }}
      - { label: "DOI", name: "doi", widget: "string"}
    identifier_field: hubmap_id  
    slug: "{{hubmap_id}}"

  - label: "Individuals"
    name: "individuals"
    folder: "src/individuals"
    create: true
    editor:
      preview: false
    fields:
      - {label: "First Name", name: "first_name", widget: "string"}
      - {label: "Middle Name", name: "middle_name", widget: "string", required: false}
      - {label: "Last Name", name: "last_name", widget: "string"}
      - {label: "ORCID", name: "orcid",widget: "string",hint: "16 digit ORCID",pattern: ['([0-9]{4})+(-)+([0-9]{4})+(-)+([0-9]{4})+(-)+([X-X0-9]{4})',"ORCID must be a 16 digit number with no alphabets except X"]}
      - {label: "title", name: "title", widget: "hidden", default: "{{first_name}}_{{last_name}}_{{orcid}}"}
    identifier_field: orcid
    slug: "{{first_name}}_{{last_name}}_{{orcid}}"

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
